# Generated by Django 4.2.2 on 2023-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indusapp', '0002_alter_binarytree_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarytree',
            name='child',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
