# Generated by Django 4.2.2 on 2023-06-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indusapp', '0006_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='childrens',
            new_name='child',
        ),
    ]
